In [1]:
import numpy as np
import pandas as pd


1.  Initial random weight ie. w1 w2

2.  predict with random weight as defined in (1)
    ypred = w1x1 +w2x2
    
3.  Calculate error  based on metrics i.e. mse
    error(E) = (y-ypred)**2  = (y- (w1x1 +w2x2))**2
    
4.  if optimiser is sgd i will take
    dEw1  = 2*(y-ypred)*(-x1)
    dEw2  = 2*(y-ypred)*(-x2)
    
5. update the weight based of dEw and learning rate(lr - 0.001)
    w1 = w1 - lr*dEw1
    w2 = w2 - lr*dEw2
    
6. got to point no 2

### Gradient Descent with single data point

In [249]:
df = pd.DataFrame([2,5,31]).T
df.columns = ["x1", "x2", "y"]

df


x1  x2   y
0   2   5  31

In [250]:
x1, x2 = 2,5
y = 31
w1,w2 = 0.3, 0.3

### Prediction

In [251]:
ypred = w1*x1 +w2*x2   

ypred

2.1

In [252]:
err = (y-ypred)**2
err

835.2099999999999

### Gradient Descent with learning rate and back propagation


In [253]:
lr = 0.01
n = 20
w1,w2 = 0.3, 0.3
for epoch in range(n):
    ypred = w1*x1 +w2*x2
    err = (y-ypred)**2
    print("epoch ",epoch,": w1: ", w1, "w2: ",w2, "error: ",err)
    #dEw1 = 2 *(y-ypred)
    
    dEw1 = 2*(y-ypred)*(-x1)
    dEw2 = 2*(y-ypred)*(-x2)
    w1 = w1 - lr*dEw1
    w2 = w2 - lr*dEw2

epoch  0 : w1:  0.3 w2:  0.3 error:  835.2099999999999
epoch  1 : w1:  1.456 w2:  3.19 error:  147.33104400000005
epoch  2 : w1:  1.9415200000000001 w2:  4.4038 error:  25.98919616159997
epoch  3 : w1:  2.1454384 w2:  4.913596 error:  4.5844942029062485
epoch  4 : w1:  2.2310841280000004 w2:  5.12771032 error:  0.8087047773926583
epoch  5 : w1:  2.2670553337600006 w2:  5.2176383344 error:  0.14265552273206467
epoch  6 : w1:  2.2821632401792007 w2:  5.255408100448 error:  0.025164434209935825
epoch  7 : w1:  2.2885085608752647 w2:  5.27127140218816 error:  0.004439006194632907
epoch  8 : w1:  2.291173595567612 w2:  5.277933988919027 error:  0.0007830406927332209
epoch  9 : w1:  2.2922929101383973 w2:  5.280732275345991 error:  0.0001381283781981485
epoch  10 : w1:  2.2927630222581272 w2:  5.281907555645316 error:  2.4365845914181457e-05
epoch  11 : w1:  2.292960469348414 w2:  5.282401173371032 error:  4.298135219270153e-06
epoch  12 : w1:  2.2930433971263344 w2:  5.282608492815833 error

In [254]:
ypred

30.999997992597965

In [21]:
w1, w2

(2.2931033901304247, 5.282758475326059)

### Gradient Descent with learning rate and early stopping

In [24]:
x1, x2 = 2,5
y = 31
w1,w2 = 0.3, 0.3
lr = 0.01
n = 20
for epoch in range(n):
    ypred = w1*x1 +w2*x2
    err = (y-ypred)**2
    print("epoch ",epoch,": ",err)
    #dEw1 = 2 *(y-ypred)
    
    dEw1 = 2*(y-ypred)*(-x1)
    dEw2 = 2*(y-ypred)*(-x2)
    w1 = w1 - lr*dEw1
    w2 = w2 - lr*dEw2
    
    if err < 0.0005:
        break

epoch  0 :  835.2099999999999
epoch  1 :  147.33104400000005
epoch  2 :  25.98919616159997
epoch  3 :  4.5844942029062485
epoch  4 :  0.8087047773926583
epoch  5 :  0.14265552273206467
epoch  6 :  0.025164434209935825
epoch  7 :  0.004439006194632907
epoch  8 :  0.0007830406927332209
epoch  9 :  0.0001381283781981485


In [25]:
ypred

30.98824719700675

In [26]:
w1, w2

(2.2927630222581272, 5.281907555645316)

### Batch Processing

In [176]:
df = pd.DataFrame({"x1":[4,9], "x2":[3,3], "y":[11,21]})
df

x1  x2   y
0   4   3  11
1   9   3  21

In [177]:
x = df.iloc[:, 0:2]
y = df.iloc[:, 2]

In [178]:
x = x.values
x

array([[4, 3],
       [9, 3]])

In [179]:
y= y.values
y

array([11, 21])

In [180]:
w = np.array([5,5])
w

array([5, 5])

In [255]:
n = 200 # Total epoch

df = pd.DataFrame({"x1":[4,9], "x2":[3,3], "y":[11,21]})
x = df.iloc[:, 0:2].values
y = df.iloc[:, 2].values
w = np.array([5,5])
lr = 0.001
for epoch in range(n):
    ypred = np.dot(x,w)
    err = 1/2 * np.sum((y -ypred)**2)
    print("epoch ",epoch,": w1: ", w[0], "w2: ",w[1], "error: ",err)
    #print("Prediction ", ypred)
    dEw1 = 2*np.dot(((y-ypred)), -x[:,0])
    dEw2 = 2*np.dot(((y-ypred)), -x[:,1])
    w1 = w[0] - lr*dEw1
    w2 = w[1] - lr*dEw2
   
    w = np.array([w1, w2])
    
    if err < 0.001:
        break
    #print(w)

epoch  0 : w1:  5 w2:  5 error:  1048.5
epoch  1 : w1:  4.106 w2:  4.622 error:  630.66825
epoch  2 : w1:  3.41492 w2:  4.3273399999999995 error:  380.3465322899999
epoch  3 : w1:  2.880893 w2:  4.097192 error:  230.37154506583644
epoch  4 : w1:  2.468418782 w2:  3.9169834339999996 error:  140.5092379850663
epoch  5 : w1:  2.1500208304400004 w2:  3.7754353653799995 error:  86.65747792609189
epoch  6 : w1:  1.9044328308350003 w2:  3.6638180674519996 error:  54.377926310528856
epoch  7 : w1:  1.7151950523917543 w2:  3.5753748562185974 error:  35.02132243333992
epoch  8 : w1:  1.5695679734427035 w2:  3.504876147308171 error:  23.406341762187875
epoch  9 : w1:  1.4576914471047817 w2:  3.448274304076546 error:  16.42912038692611
epoch  10 : w1:  1.3719339106484836 w2:  3.4024364962556173 error:  12.23029326801773
epoch  11 : w1:  1.3063886852747395 w2:  3.364937937359833 error:  9.696010072890719
epoch  12 : w1:  1.256484121217373 w2:  3.3339018541634493 error:  8.15901965536169
epoch  13 :

In [256]:
ypred

array([12.45448531, 20.25630523])

In [257]:
err

1.3343047149254446

In [245]:
x

array([[4, 3],
       [9, 3]])